(define (weight branch)
  (let ((structure (branch-structure branch)))
    (if (pair? structure)
      (total-weight structure)
      structure)))

(define (total-weight mobile)
  (if (pair? mobile)
    (+ (weight (left-branch mobile))
       (weight (right-branch mobile)))
    mobile))

(define (balanced? mobile)
  (define (torque branch)
    (* (weight branch) (branch-length branch)))

  (or (not (pair? mobile))
      (let ((left (left-branch mobile))
            (right (right-branch mobile)))
        (and (= (torque left)
                (torque right))
             (balanced? (branch-structure left))
             (balanced? (branch-structure right))))))